resources:
  - type: module
    url: /local/button-card.js
  - type: js
    url: /local/kiosk.js
title: Home
views:
  - badges: []
    panel: true
    cards:
      - type: horizontal-stack
        cards:
        - type: vertical-stack
          cards:
            - type: weather-forecast
              entity: weather.home
        - type: vertical-stack
          cards:
          - type: horizontal-stack
            cards:
              - entity: scene.default_day
                icon: 'mdi:lightbulb'
                type: entity-button
              - entity: scene.evening_low
                icon: 'mdi:floor-lamp'
                type: entity-button
              - entity: scene.evening
                icon: 'mdi:lightbulb-on'
                type: entity-button
              - entity: scene.dinner
                icon: 'mdi:ceiling-light'
                type: entity-button
          - type: horizontal-stack
            cards:
              - type: 'custom:button-card'
                entity: input_select.mode
                name: Morning
                icon: mdi:weather-sunset-up
                tap_action: call-service
                service: input_select.select_option
                service_data:
                  option: Morning
                show_state: false
                state:
                  - operator: '!='
                    value: "Morning"
                    color: var(--disabled-text-color)
              - type: 'custom:button-card'
                entity: input_select.mode
                name: Day
                icon: mdi:weather-sunny
                tap_action: call-service
                service: input_select.select_option
                service_data:
                  option: Day
                show_state: false
                state:
                  - operator: '!='
                    value: "Day"
                    color: var(--disabled-text-color)
              - type: 'custom:button-card'
                entity: input_select.mode
                name: Evening
                icon: mdi:weather-sunset
                tap_action: call-service
                service: input_select.select_option
                service_data:
                  option: Evening
                show_state: false
                state:
                  - operator: '!='
                    value: "Evening"
                    color: var(--disabled-text-color)
              - type: 'custom:button-card'
                entity: input_select.mode
                name: Night
                icon: mdi:weather-night
                tap_action: call-service
                service: input_select.select_option
                service_data:
                  option: Night
                show_state: false
                state:
                  - operator: '!='
                    value: "Night"
                    color: var(--disabled-text-color)
          
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - entity: light.basement_main_lights_1
          - entity: light.basement_main_lights_2
          - entity: light.basement_accent_lights_1
          - entity: light.basement_accent_lights_2
          - entity: switch.basement_crown_lights
          - entity: light.bar_main_lights
          - entity: light.bar_pendant_lights
          - entity: switch.bar_undercabinet_lights
        title: Lights
        type: entities
      - entities:
          - entity: scene.basement_high
          - entity: scene.basement_medium
          - entity: scene.basement_low
          - entity: scene.basement_movie
          - entity: scene.basement_off
        title: Scenes
        type: entities
    title: Basement
  - badges: []
    cards:
      - entities:
          - entity: input_select.mode
          - entity: input_boolean.guests
          - entity: input_boolean.vacation_mode
          - entity: input_boolean.detect_motion
          - entity: input_boolean.detect_motion_basement
          - entity: input_boolean.bedroom_motion_lights
        show_header_toggle: false
        title: Settings
        type: entities
      - entities:
          - entity: input_select.presence
        type: glance
    title: Settings
  - badges: []
    cards: []
    path: media
    title: Media
