resources: !include lovelace/resources/resources.yaml

decluttering_templates:
  !include_dir_named lovelace/templates

title: Home
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/basement.yaml
  - !include lovelace/views/settings.yaml
